import { Fund, Portfolio, Favorite, FundSummary } from '../types';

export const mockFunds: Fund[] = [
  {
    id: '1',
    name: 'Vanguard Total Stock Market Index Fund',
    ticker: 'VTSAX',
    category: 'Large Blend',
    expenseRatio: 0.04,
    aum: 1300000,
    ytdReturn: 12.5,
    oneYearReturn: 18.2,
    threeYearReturn: 10.1,
    fiveYearReturn: 14.8,
    riskLevel: 'Medium',
    description: 'This fund seeks to track the performance of the CRSP US Total Market Index.',
    inceptionDate: '2000-11-13',
    minimumInvestment: 3000,
  },
  {
    id: '2',
    name: 'Fidelity 500 Index Fund',
    ticker: 'FXAIX',
    category: 'Large Blend',
    expenseRatio: 0.015,
    aum: 450000,
    ytdReturn: 11.8,
    oneYearReturn: 17.5,
    threeYearReturn: 9.8,
    fiveYearReturn: 14.2,
    riskLevel: 'Medium',
    description: 'The fund seeks to provide investment results that correspond to the total return of stocks of large-capitalization US companies.',
    inceptionDate: '1988-02-17',
    minimumInvestment: 0,
  },
  {
    id: '3',
    name: 'iShares Core US Aggregate Bond ETF',
    ticker: 'AGG',
    category: 'Intermediate Core Bond',
    expenseRatio: 0.03,
    aum: 95000,
    ytdReturn: -2.1,
    oneYearReturn: 1.2,
    threeYearReturn: -3.5,
    fiveYearReturn: 0.8,
    riskLevel: 'Low',
    description: 'The fund seeks to track the investment results of the Bloomberg US Aggregate Bond Index.',
    inceptionDate: '2003-09-22',
    minimumInvestment: 0,
  },
  {
    id: '4',
    name: 'ARK Innovation ETF',
    ticker: 'ARKK',
    category: 'Disruptive Innovation',
    expenseRatio: 0.75,
    aum: 8500,
    ytdReturn: 42.3,
    oneYearReturn: 68.5,
    threeYearReturn: -12.4,
    fiveYearReturn: 15.2,
    riskLevel: 'High',
    description: 'The fund invests in companies that are focused on disruptive innovation.',
    inceptionDate: '2014-10-31',
    minimumInvestment: 0,
  },
  {
    id: '5',
    name: 'Vanguard Total International Stock Index Fund',
    ticker: 'VTIAX',
    category: 'Foreign Large Blend',
    expenseRatio: 0.11,
    aum: 560000,
    ytdReturn: 8.2,
    oneYearReturn: 15.3,
    threeYearReturn: 3.5,
    fiveYearReturn: 7.8,
    riskLevel: 'Medium',
    description: 'The fund seeks to track the performance of the FTSE Global All Cap ex US Index.',
    inceptionDate: '2010-11-29',
    minimumInvestment: 3000,
  },
];

export const mockFundSummaries: FundSummary[] = mockFunds.map((fund) => ({
  id: fund.id,
  name: fund.name,
  ticker: fund.ticker,
  category: fund.category,
  ytdReturn: fund.ytdReturn,
  expenseRatio: fund.expenseRatio,
  riskLevel: fund.riskLevel,
}));

export const mockPortfolios: Portfolio[] = [
  {
    id: 'p1',
    name: 'My Retirement Portfolio',
    userId: 'user1',
    holdings: [
      {
        fundId: '1',
        fund: mockFundSummaries[0],
        shares: 100,
        averageCost: 95.5,
        currentValue: 10800,
        totalReturn: 1250,
        totalReturnPercentage: 13.1,
      },
      {
        fundId: '3',
        fund: mockFundSummaries[2],
        shares: 50,
        averageCost: 107.2,
        currentValue: 5250,
        totalReturn: -110,
        totalReturnPercentage: -2.1,
      },
    ],
    totalValue: 16050,
    totalCost: 14910,
    totalReturn: 1140,
    totalReturnPercentage: 7.6,
    createdAt: '2023-01-15T10:00:00Z',
    updatedAt: '2024-01-10T15:30:00Z',
  },
  {
    id: 'p2',
    name: 'Growth Portfolio',
    userId: 'user1',
    holdings: [
      {
        fundId: '4',
        fund: mockFundSummaries[3],
        shares: 25,
        averageCost: 68.5,
        currentValue: 2400,
        totalReturn: 687.5,
        totalReturnPercentage: 40.2,
      },
    ],
    totalValue: 2400,
    totalCost: 1712.5,
    totalReturn: 687.5,
    totalReturnPercentage: 40.2,
    createdAt: '2023-06-20T14:00:00Z',
    updatedAt: '2024-01-10T15:30:00Z',
  },
];

export const mockFavorites: Favorite[] = [
  {
    id: 'f1',
    userId: 'user1',
    fundId: '1',
    fund: mockFundSummaries[0],
    createdAt: '2023-03-10T12:00:00Z',
  },
  {
    id: 'f2',
    userId: 'user1',
    fundId: '2',
    fund: mockFundSummaries[1],
    createdAt: '2023-04-15T09:30:00Z',
  },
  {
    id: 'f3',
    userId: 'user1',
    fundId: '5',
    fund: mockFundSummaries[4],
    createdAt: '2023-05-22T16:45:00Z',
  },
];
